def get_footer_and_js():
    return """
    </main>

    <!-- Deck Footer -->
    <footer class="deck-footer">
      <div style="display: flex; align-items: center; gap: 12px;">
        <button class="nav-btn" onclick="openDrawer()" title="View All Slides">☰ ALL SLIDES</button>
        <span style="font-family: var(--font-mono); font-size: 0.72rem; color: var(--sand-muted);">USE [← / →] KEYS</span>
      </div>

      <!-- 30 Progress Dots -->
      <div class="progress-dots" id="progressDots">
        <!-- Generated by JS -->
      </div>

      <div class="nav-buttons">
        <button class="nav-btn" id="prevBtn" title="Previous Slide (Arrow Left)">← PREV</button>
        <button class="nav-btn" id="nextBtn" title="Next Slide (Arrow Right)">NEXT →</button>
      </div>
    </footer>
  </div>

  <script>
    (function() {
      'use strict';

      // =====================================================================
      // STATE & ELEMENT SELECTORS
      // =====================================================================
      const slides = Array.from(document.querySelectorAll('.slide'));
      const totalSlides = slides.length;
      let currentIndex = 0;

      const slideCounter = document.getElementById('slideCounter');
      const prevBtn = document.getElementById('prevBtn');
      const nextBtn = document.getElementById('nextBtn');
      const progressDots = document.getElementById('progressDots');
      const themeBtn = document.getElementById('themeBtn');
      const fullscreenBtn = document.getElementById('fullscreenBtn');
      const nativeSlidePicker = document.getElementById('nativeSlidePicker');

      const drawerOverlay = document.getElementById('drawerOverlay');
      const drawerBackdrop = document.getElementById('drawerBackdrop');
      const drawerCloseBtn = document.getElementById('drawerCloseBtn');
      const drawerList = document.getElementById('drawerList');
      const drawerSearchInput = document.getElementById('drawerSearchInput');
      const drawerSearchClear = document.getElementById('drawerSearchClear');
      const drawerFilterPills = document.getElementById('drawerFilterPills');
      const deckDrawerTrigger = document.getElementById('deckDrawerTrigger');
      let isDrawerOpen = false;

      // =====================================================================
      // PROGRESS DOTS CREATION
      // =====================================================================
      if (progressDots) {
        progressDots.innerHTML = '';
        slides.forEach((_, idx) => {
          const dot = document.createElement('div');
          dot.className = `dot ${idx === 0 ? 'active' : ''}`;
          dot.title = `Go to slide ${idx + 1}`;
          dot.addEventListener('click', () => goToSlide(idx));
          progressDots.appendChild(dot);
        });
      }

      // =====================================================================
      // SLIDE NAVIGATION
      // =====================================================================
      function updateSlide(newIndex) {
        if (newIndex < 0 || newIndex >= totalSlides) return;

        slides[currentIndex].classList.remove('active');
        currentIndex = newIndex;
        slides[currentIndex].classList.add('active');

        // Scroll slide content to top
        slides[currentIndex].scrollTop = 0;

        // Update Counter
        const formattedNum = String(currentIndex + 1).padStart(2, '0');
        const formattedTotal = String(totalSlides).padStart(2, '0');
        if (slideCounter) {
          slideCounter.textContent = `SLIDE ${formattedNum} / ${formattedTotal}`;
        }

        // Update Prev/Next Buttons
        if (prevBtn) prevBtn.disabled = currentIndex === 0;
        if (nextBtn) nextBtn.disabled = currentIndex === totalSlides - 1;

        // Update Progress Dots
        if (progressDots) {
          const dots = progressDots.querySelectorAll('.dot');
          dots.forEach((dot, idx) => {
            dot.classList.toggle('active', idx === currentIndex);
          });
        }

        // Sync Native Mobile Picker
        if (nativeSlidePicker) {
          nativeSlidePicker.value = currentIndex;
        }

        // Sync Drawer
        syncDrawerActiveState();

        // Update URL Hash without scroll jump
        try {
          history.replaceState(null, '', '#' + (currentIndex + 1));
        } catch(e) {}
      }

      function goToSlide(index) {
        updateSlide(index);
      }

      function nextSlide() {
        if (currentIndex < totalSlides - 1) updateSlide(currentIndex + 1);
      }

      function prevSlide() {
        if (currentIndex > 0) updateSlide(currentIndex - 1);
      }

      window.goToSlide = goToSlide;
      window.nextSlide = nextSlide;
      window.prevSlide = prevSlide;

      if (prevBtn) prevBtn.addEventListener('click', prevSlide);
      if (nextBtn) nextBtn.addEventListener('click', nextSlide);

      // Keyboard navigation
      window.addEventListener('keydown', (e) => {
        if (isDrawerOpen) return;
        if (e.target.tagName === 'INPUT' || e.target.tagName === 'SELECT') return;

        if (e.key === 'ArrowRight' || e.key === 'PageDown' || (e.key === ' ' && !e.shiftKey)) {
          e.preventDefault();
          nextSlide();
        } else if (e.key === 'ArrowLeft' || e.key === 'PageUp' || (e.key === ' ' && e.shiftKey)) {
          e.preventDefault();
          prevSlide();
        } else if (e.key === 'Home') {
          e.preventDefault();
          goToSlide(0);
        } else if (e.key === 'End') {
          e.preventDefault();
          goToSlide(totalSlides - 1);
        }
      });

      // Mobile Touch Swipe Handling
      let touchStartX = 0;
      let touchStartY = 0;
      let touchMoved = false;

      window.addEventListener('touchstart', (e) => {
        if (isDrawerOpen) return;
        touchStartX = e.touches[0].clientX;
        touchStartY = e.touches[0].clientY;
        touchMoved = false;
      }, { passive: true });

      window.addEventListener('touchmove', (e) => {
        if (isDrawerOpen) return;
        const diffX = e.touches[0].clientX - touchStartX;
        const diffY = e.touches[0].clientY - touchStartY;
        if (Math.abs(diffX) > 10 || Math.abs(diffY) > 10) {
          touchMoved = true;
        }
      }, { passive: true });

      window.addEventListener('touchend', (e) => {
        if (isDrawerOpen || !touchMoved) return;
        const diffX = e.changedTouches[0].clientX - touchStartX;
        const diffY = e.changedTouches[0].clientY - touchStartY;

        // Horizontal swipe detection
        if (Math.abs(diffX) > 45 && Math.abs(diffX) > Math.abs(diffY) * 1.5) {
          if (diffX < 0) nextSlide();
          else prevSlide();
        }
      }, { passive: true });

      // Native Slide Picker change listener
      if (nativeSlidePicker) {
        nativeSlidePicker.addEventListener('change', (e) => {
          const val = parseInt(e.target.value, 10);
          if (!isNaN(val)) goToSlide(val);
        });
      }

      // =====================================================================
      // FULLSCREEN API
      // =====================================================================
      if (fullscreenBtn) {
        fullscreenBtn.addEventListener('click', () => {
          if (!document.fullscreenElement) {
            document.documentElement.requestFullscreen().catch(() => {});
            fullscreenBtn.textContent = '⛶ EXIT';
          } else {
            document.exitFullscreen().catch(() => {});
            fullscreenBtn.textContent = '⛶ EXPAND';
          }
        });
      }

      // =====================================================================
      // THEME CONTROLLER
      // =====================================================================
      const themes = [
        { id: "linen", name: "Porcelain & Slate" },
        { id: "coastal", name: "Atlantic Navy" },
        { id: "obsidian", name: "Obsidian & Gold" }
      ];
      let currentThemeIdx = 0;

      function applyTheme(idx) {
        currentThemeIdx = idx % themes.length;
        const selected = themes[currentThemeIdx];
        document.documentElement.setAttribute('data-theme', selected.id);
        if (themeBtn) {
          themeBtn.textContent = `🎨 PALETTE: ${selected.name}`;
        }
        try { localStorage.setItem('florida-theme', selected.id); } catch(e) {}
      }

      const savedTheme = (function() {
        try { return localStorage.getItem('florida-theme') || 'linen'; } catch(e) { return 'linen'; }
      })();
      const initialIdx = themes.findIndex(t => t.id === savedTheme);
      applyTheme(initialIdx >= 0 ? initialIdx : 0);

      if (themeBtn) {
        themeBtn.addEventListener('click', () => {
          applyTheme(currentThemeIdx + 1);
        });
      }

      // =====================================================================
      // SLIDE 3: INTERACTIVE FLORIDA CARTOGRAPHY
      // =====================================================================
      const waypoints = [
        {
          id: 0,
          label: "MILESTONE 01 • INBOUND GATEWAY",
          title: "Miami International Airport & Cultural District",
          coords: "25.7959° N, 80.2870° W",
          metrics: "0 Miles Driven • Sea Level (6 ft)",
          tag: "ARRIVAL",
          tagClass: "tag-gold",
          desc: "Touchdown at MIA. Consolidated Rental Car Center dispatch via MIA Mover monorail. Afternoon exploration of Wynwood contemporary street murals and Little Havana's vibrant Calle Ocho."
        },
        {
          id: 1,
          label: "MILESTONE 02 • THE UPPER KEYS",
          title: "Key Largo & John Pennekamp Coral Reef",
          coords: "25.1246° N, 80.4042° W",
          metrics: "62 Miles from MIA • Mile Marker 102.5",
          tag: "SNORKEL REEF",
          tagClass: "tag-teal",
          desc: "First underwater park in the United States. 2.5-hour boat excursion snorkeling shallow living coral gardens at Grecian Rocks and Molasses Reef. Teeming with parrotfish, sea fans, and marine turtles."
        },
        {
          id: 2,
          label: "MILESTONE 03 • THE MIDDLE KEYS",
          title: "Seven Mile Bridge & Bahia Honda State Park",
          coords: "24.6644° N, 81.2581° W",
          metrics: "128 Miles from MIA • Mile Marker 37",
          tag: "OCEAN LAGOON",
          tagClass: "tag-teal",
          desc: "Traversing Henry Flagler's iconic Seven Mile Bridge suspended above turquoise ocean waters. Hiking the historic Old Bahia Honda rail bridge overlook and swimming in pristine Calusa Beach lagoons."
        },
        {
          id: 3,
          label: "MILESTONE 04 • END OF THE ROAD",
          title: "Key West Old Town & Mallory Square",
          coords: "24.5551° N, 81.7800° W",
          metrics: "165 Miles from MIA • Mile Marker 0",
          tag: "SOUTHERNMOST",
          tagClass: "tag-terracotta",
          desc: "The southernmost point of the continental US (90 miles to Cuba). Victorian Conch architecture, Ernest Hemingway's estate with 50+ six-toed cats, Fort Zachary Taylor, and sunset at Mallory Square."
        },
        {
          id: 4,
          label: "MILESTONE 05 • UNESCO WILDERNESS",
          title: "Everglades National Park (Shark Valley)",
          coords: "25.7467° N, 80.7656° W",
          metrics: "140 Miles from Key West • Tamiami Trail",
          tag: "SAWGRASS SAFARI",
          tagClass: "tag-teal",
          desc: "1.5-million-acre subtropical river of grass. 2-hour naturalist-guided open tram loop through sawgrass prairie, observing dozens of wild alligators, anhingas, and climbing the 65-foot observation tower."
        },
        {
          id: 5,
          label: "MILESTONE 06 • THEME PARK THRILLS",
          title: "Universal Studios & Islands of Adventure",
          coords: "28.4744° N, 81.4678° W",
          metrics: "215 Miles from Shark Valley • Orlando Base",
          tag: "WIZARDING WORLD",
          tagClass: "tag-gold",
          desc: "2-Park immersion: Jurassic World VelociCoaster (70 mph launch), Hagrid's Magical Creatures Motorbike Adventure, Diagon Alley, and riding the Hogwarts Express train between parks."
        },
        {
          id: 6,
          label: "MILESTONE 07 • THE MAGIC KINGDOM",
          title: "Walt Disney World (Magic Kingdom & Studios)",
          coords: "28.4177° N, 81.5812° W",
          metrics: "12 Miles from Universal • Orlando Base",
          tag: "DISNEY WORLD",
          tagClass: "tag-gold",
          desc: "Rope-dropping Space Mountain, riding TRON Lightcycle / Run, sailing with Pirates of the Caribbean, tasting fresh pineapple Dole Whip, and the Happily Ever After fireworks over Cinderella Castle."
        },
        {
          id: 7,
          label: "MILESTONE 08 • OUTBOUND HUB",
          title: "Orlando International Airport (MCO)",
          coords: "28.4312° N, 81.3081° W",
          metrics: "18 Miles from Disney • Departure Hub",
          tag: "DEPARTURE",
          tagClass: "tag-terracotta",
          desc: "Effortless consolidated garage rental car drop-off (zero shuttles). Expedited TSA clearance via MCO Reserve, followed by a non-stop 2h 45m flight on United Airlines returning directly to Newark (EWR)."
        }
      ];

      window.selectMapStage = function(idx) {
        // Update pills
        const pills = document.querySelectorAll('#mapPillContainer .stage-pill');
        pills.forEach((p, i) => p.classList.toggle('active', i === idx));

        // Update SVG circles
        const nodes = document.querySelectorAll('.map-node');
        nodes.forEach((n, i) => {
          if (i === idx) {
            n.setAttribute('r', '11');
            n.setAttribute('stroke-width', '3.5');
          } else {
            n.setAttribute('r', (i === 0 || i === 3 || i === 7) ? '9' : '8');
            n.setAttribute('stroke-width', '2');
          }
        });

        // Update detail card
        const card = document.getElementById('waypointDetailCard');
        const wp = waypoints[idx];
        if (!card || !wp) return;

        card.innerHTML = `
          <div>
            <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.6rem;">
              <div class="card-label">${wp.label}</div>
              <span class="tag ${wp.tagClass}">${wp.tag}</span>
            </div>
            <h3 class="card-heading" style="margin-bottom: 0.4rem;">${wp.title}</h3>
            
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 1rem;">
              <div class="stat-box" style="padding: 8px 12px;">
                <div style="font-family: var(--font-mono); font-size: 0.68rem; color: var(--sand-muted);">COORDINATES</div>
                <div style="font-family: var(--font-mono); font-size: 0.88rem; font-weight: 700; color: var(--text-title);">${wp.coords}</div>
              </div>
              <div class="stat-box" style="padding: 8px 12px;">
                <div style="font-family: var(--font-mono); font-size: 0.68rem; color: var(--sand-muted);">CORRIDOR METRIC</div>
                <div style="font-family: var(--font-mono); font-size: 0.88rem; font-weight: 700; color: var(--gold-primary);">${wp.metrics}</div>
              </div>
            </div>

            <p class="card-body" style="font-size: 0.96rem; line-height: 1.55;">${wp.desc}</p>
          </div>

          <div style="margin-top: 1rem; padding-top: 0.8rem; border-top: 1px solid var(--border-subtle); display: flex; justify-content: space-between; align-items: center;">
            <span style="font-family: var(--font-mono); font-size: 0.74rem; color: var(--sand-muted);">OPEN-JAW CORRIDOR</span>
            <button class="nav-btn" style="padding: 4px 10px; font-size: 0.72rem;" onclick="goToSlide(${idx <= 3 ? idx + 7 : (idx === 4 ? 16 : (idx === 5 ? 19 : (idx === 6 ? 22 : 27)))})">JUMP TO ITINERARY →</button>
          </div>
        `;
      };

      // =====================================================================
      // SLIDE 5: TRANSIT & VEHICLE SWITCHER
      // =====================================================================
      const transitData = [
        {
          label: "RECOMMENDED EXPEDITION CHOICE",
          title: "Mid-size SUV or Standard Sedan",
          tagText: "OPTIMAL AGILITY",
          tagClass: "tag-gold",
          cost: "$385 total",
          costSub: "8 Days + Intrastate Drop",
          mpg: "32 MPG Hwy",
          mpgSub: "585 miles = ~$65 gas",
          highlights: [
            "<strong>Ideal Trunk Storage:</strong> Ample locked trunk space to keep two large suitcases completely hidden out of sight during beach and Everglades stops.",
            "<strong>Parking Agility:</strong> Narrow historic lanes and tight parking spaces in Key West Old Town are easily navigated without maneuvering stress.",
            "<strong>Near-Zero Drop Fee:</strong> Intrastate drop fee between Miami (MIA) and Orlando (MCO) is under $25 with Alamo, Enterprise, or National.",
            "<strong>High Highway Efficiency:</strong> 32 mpg average ensures only 2 full fuel fill-ups across the entire 585-mile journey."
          ]
        },
        {
          label: "ALTERNATIVE CLEAN ENERGY OPTION",
          title: "Compact Electric Vehicle (Tesla Model 3 / Y)",
          tagText: "HIGH TECH CORRIDOR",
          tagClass: "tag-teal",
          cost: "$410 total",
          costSub: "8 Days + Drop Fee",
          mpg: "Supercharger",
          mpgSub: "Abundant on Turnpike & US-1",
          highlights: [
            "<strong>Robust Charging Infrastructure:</strong> Tesla Supercharger stations are located at Key Largo, Marathon, Florida City, and every Turnpike service plaza.",
            "<strong>Smooth Instant Torque:</strong> Silent acceleration on highway on-ramps and air-conditioned cabin pre-cooling via app.",
            "<strong>Charging Stop Time:</strong> Adds 20–25 minutes of dwell time every 200 miles; ensure hotel has overnight Level 2 destination chargers.",
            "<strong>Verdict:</strong> Excellent modern road-trip choice if you enjoy EV technology."
          ]
        },
        {
          label: "EXCESSIVE CAPACITY CLASS",
          title: "Full-size SUV or Minivan",
          tagText: "UNNECESSARY COST",
          tagClass: "tag-terracotta",
          cost: "$540 total",
          costSub: "+40% higher rental rate",
          mpg: "18 MPG Hwy",
          mpgSub: "Gas cost exceeds $120",
          highlights: [
            "<strong>Excessive for Two Travelers:</strong> 7-passenger space is wasted when traveling as a couple.",
            "<strong>Key West Parking Penalty:</strong> Historic Old Town curbside spaces are notoriously small; larger SUVs struggle to find street parking.",
            "<strong>Higher Fuel Expense:</strong> Low fuel economy adds $55+ in unnecessary gasoline expenses.",
            "<strong>Verdict:</strong> Avoid. Stick to a nimble mid-size vehicle."
          ]
        },
        {
          label: "INFLEXIBLE MASS TRANSIT",
          title: "Airport Shuttles & Ride-Share Only",
          tagText: "RIGID & PRICEY",
          tagClass: "tag-terracotta",
          cost: "$720+ total",
          costSub: "Multiple long-distance legs",
          mpg: "Zero Freedom",
          mpgSub: "No Everglades stopover",
          highlights: [
            "<strong>Zero Everglades Access:</strong> Public shuttles do not stop at Shark Valley or Tamiami Trail in the Everglades.",
            "<strong>Rigid Keys Timetables:</strong> Keys shuttles run on fixed hours, eliminating spontaneous snorkeling or bridge photo stops.",
            "<strong>Sky-High Ride-Share Rates:</strong> Long-haul Uber/Lyft between Miami and Orlando costs $250+ for a single one-way trip.",
            "<strong>Verdict:</strong> Non-viable for a multi-ecosystem expedition."
          ]
        }
      ];

      window.switchTransitOption = function(slideNum, optIdx) {
        const cards = document.querySelectorAll(`[data-slide="${slideNum}"] .transit-option-card`);
        cards.forEach((c, idx) => c.classList.toggle('active', idx === optIdx));

        const data = transitData[optIdx];
        const container = document.getElementById(`transitDetailCard-${slideNum}`);
        if (!data || !container) return;

        container.innerHTML = `
          <div>
            <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 0.6rem;">
              <div class="card-label">${data.label}</div>
              <span class="tag ${data.tagClass}">${data.tagText}</span>
            </div>
            <h3 class="card-heading" style="margin-bottom: 0.4rem;">${data.title}</h3>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-bottom: 1rem;">
              <div class="stat-box" style="padding: 8px 12px;">
                <div style="font-family: var(--font-mono); font-size: 0.68rem; color: var(--sand-muted);">TOTAL ESTIMATED COST</div>
                <div style="font-family: var(--font-serif); font-size: 1.3rem; font-weight: 700; color: var(--gold-primary);">${data.cost}</div>
                <div style="font-size: 0.72rem; color: var(--sand-muted);">${data.costSub}</div>
              </div>
              <div class="stat-box" style="padding: 8px 12px;">
                <div style="font-family: var(--font-mono); font-size: 0.68rem; color: var(--sand-muted);">FUEL / EFFICIENCY</div>
                <div style="font-family: var(--font-serif); font-size: 1.3rem; font-weight: 700; color: var(--teal-ocean);">${data.mpg}</div>
                <div style="font-size: 0.72rem; color: var(--sand-muted);">${data.mpgSub}</div>
              </div>
            </div>

            <ul class="highlight-list" style="font-size: 0.94rem;">
              ${data.highlights.map(h => `<li>${h}</li>`).join('')}
            </ul>
          </div>
        `;
      };

      // =====================================================================
      // SLIDE NAVIGATION DRAWER ENGINE
      // =====================================================================
      const slideMetaMap = {
        1: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'COVER' },
        2: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'CORRIDOR' },
        3: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'CARTOGRAPHY' },
        4: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'WEATHER' },
        5: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'HIGHWAY' },
        6: { cat: ['all', 'overview', 'glades'], primaryCat: 'glades', tag: 'WILDLIFE' },
        7: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'PACKING' },
        8: { cat: ['all', 'keys'], primaryCat: 'keys', tag: 'DAY 1: MIA' },
        9: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'NIGHT 1 BASE' },
        10: { cat: ['all', 'dining'], primaryCat: 'dining', tag: 'CUBAN FEAST' },
        11: { cat: ['all', 'keys'], primaryCat: 'keys', tag: 'DAY 2: REEF' },
        12: { cat: ['all', 'keys'], primaryCat: 'keys', tag: 'SEVEN MILE' },
        13: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'NIGHT 2 BASE' },
        14: { cat: ['all', 'keys'], primaryCat: 'keys', tag: 'DAY 3: KEY WEST' },
        15: { cat: ['all', 'dining'], primaryCat: 'dining', tag: 'KEY LIME' },
        16: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'NIGHT 3 BASE' },
        17: { cat: ['all', 'glades'], primaryCat: 'glades', tag: 'DAY 4: GLADES' },
        18: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'TURNPIKE' },
        19: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'ORLANDO BASE' },
        20: { cat: ['all', 'parks'], primaryCat: 'parks', tag: 'DAY 5: UNIVERSAL' },
        21: { cat: ['all', 'parks'], primaryCat: 'parks', tag: 'COASTER TACTICS' },
        22: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'NIGHT 5 REST' },
        23: { cat: ['all', 'parks'], primaryCat: 'parks', tag: 'DAY 6: DISNEY' },
        24: { cat: ['all', 'parks'], primaryCat: 'parks', tag: 'LIGHTNING LANE' },
        25: { cat: ['all', 'retreat'], primaryCat: 'retreat', tag: 'NIGHT 6 REST' },
        26: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'DAY 7: CANALS' },
        27: { cat: ['all', 'dining'], primaryCat: 'dining', tag: 'SMOKEHOUSE' },
        28: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'DAY 8: MCO' },
        29: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'LEDGER ($3,520)' },
        30: { cat: ['all', 'overview'], primaryCat: 'overview', tag: 'SOS DIRECTORY' }
      };

      const slideDirectoryData = slides.map((slideEl, index) => {
        const slideNum = index + 1;
        const eyebrowEl = slideEl.querySelector('.slide-eyebrow');
        const titleEl = slideEl.querySelector('.slide-title');
        const subtitleEl = slideEl.querySelector('.slide-subtitle');

        const eyebrow = eyebrowEl ? eyebrowEl.textContent.trim() : `Milestone ${slideNum}`;
        const title = titleEl ? titleEl.textContent.trim() : `Slide ${slideNum}`;
        const subtitle = subtitleEl ? subtitleEl.textContent.trim() : '';

        const meta = slideMetaMap[slideNum] || { cat: ['all'], primaryCat: 'overview', tag: `SLIDE ${slideNum}` };

        return {
          index,
          num: slideNum,
          formattedNum: String(slideNum).padStart(2, '0'),
          eyebrow,
          title,
          subtitle,
          categories: meta.cat,
          primaryCat: meta.primaryCat,
          tag: meta.tag
        };
      });

      let currentDrawerFilter = 'all';
      let currentDrawerSearch = '';

      function renderDrawerItems() {
        if (!drawerList) return;

        const term = currentDrawerSearch.toLowerCase().trim();
        const filtered = slideDirectoryData.filter(item => {
          if (currentDrawerFilter !== 'all' && !item.categories.includes(currentDrawerFilter)) {
            return false;
          }
          if (term) {
            const numStr = String(item.num);
            const matchTitle = item.title.toLowerCase().includes(term);
            const matchEyebrow = item.eyebrow.toLowerCase().includes(term);
            const matchSubtitle = item.subtitle.toLowerCase().includes(term);
            const matchTag = item.tag.toLowerCase().includes(term);
            const matchNum = numStr === term || item.formattedNum === term || `slide ${numStr}`.includes(term);
            return matchTitle || matchEyebrow || matchSubtitle || matchTag || matchNum;
          }
          return true;
        });

        if (filtered.length === 0) {
          drawerList.innerHTML = `
            <div style="padding: 2.5rem 1rem; text-align: center; color: var(--sand-muted);">
              <div style="font-size: 2rem; margin-bottom: 0.5rem; opacity: 0.7;">🔍</div>
              <div style="font-family: var(--font-serif); font-size: 1.15rem; color: var(--text-title); margin-bottom: 0.35rem;">No Milestones Found</div>
              <div style="font-size: 0.82rem;">No slides match "${currentDrawerSearch}". Try searching by park, key, or day.</div>
            </div>
          `;
          return;
        }

        drawerList.innerHTML = filtered.map(item => {
          const isActive = item.index === currentIndex;
          return `
            <div class="drawer-slide-item ${isActive ? 'active' : ''}" onclick="goToSlide(${item.index}); closeDrawer();">
              <div class="drawer-slide-num">${item.formattedNum}</div>
              <div class="drawer-slide-content">
                <div class="drawer-slide-meta">
                  <span class="drawer-slide-tag">${item.tag}</span>
                  ${isActive ? '<span class="drawer-slide-current-badge">● CURRENT</span>' : ''}
                </div>
                <div class="drawer-slide-title">${item.title}</div>
                ${item.subtitle ? `<div class="drawer-slide-desc">${item.subtitle.substring(0, 85)}...</div>` : ''}
              </div>
              <div class="drawer-slide-arrow">→</div>
            </div>
          `;
        }).join('');
      }

      function syncDrawerActiveState() {
        if (!drawerList) return;
        const items = drawerList.querySelectorAll('.drawer-slide-item');
        items.forEach((el, idx) => {
          el.classList.toggle('active', idx === currentIndex);
        });
      }

      function openDrawer() {
        if (!drawerOverlay) return;
        isDrawerOpen = true;
        drawerOverlay.classList.add('active');
        drawerOverlay.setAttribute('aria-hidden', 'false');
        renderDrawerItems();
      }

      function closeDrawer() {
        if (!drawerOverlay) return;
        isDrawerOpen = false;
        drawerOverlay.classList.remove('active');
        drawerOverlay.setAttribute('aria-hidden', 'true');
      }

      window.openDrawer = openDrawer;
      window.closeDrawer = closeDrawer;

      if (deckDrawerTrigger) deckDrawerTrigger.addEventListener('click', openDrawer);
      if (drawerCloseBtn) drawerCloseBtn.addEventListener('click', closeDrawer);
      if (drawerBackdrop) drawerBackdrop.addEventListener('click', closeDrawer);

      if (drawerSearchInput) {
        drawerSearchInput.addEventListener('input', (e) => {
          currentDrawerSearch = e.target.value;
          if (drawerSearchClear) {
            drawerSearchClear.style.display = currentDrawerSearch ? 'block' : 'none';
          }
          renderDrawerItems();
        });
      }

      if (drawerSearchClear) {
        drawerSearchClear.addEventListener('click', () => {
          currentDrawerSearch = '';
          drawerSearchInput.value = '';
          drawerSearchClear.style.display = 'none';
          renderDrawerItems();
        });
      }

      if (drawerFilterPills) {
        drawerFilterPills.addEventListener('click', (e) => {
          const pill = e.target.closest('.drawer-filter-pill');
          if (!pill) return;
          currentDrawerFilter = pill.getAttribute('data-filter') || 'all';
          drawerFilterPills.querySelectorAll('.drawer-filter-pill').forEach(p => {
            p.classList.toggle('active', p === pill);
          });
          renderDrawerItems();
        });
      }

      // Initialize Dynamic Widgets
      try {
        selectMapStage(0);
        switchTransitOption(5, 0);
        renderDrawerItems();
      } catch(e) {
        console.warn(e);
      }

      // Read Initial Slide from URL Hash
      const hash = window.location.hash.replace('#', '');
      const hashNum = parseInt(hash, 10);
      if (!isNaN(hashNum) && hashNum >= 1 && hashNum <= totalSlides) {
        updateSlide(hashNum - 1);
      } else {
        updateSlide(0);
      }

    })();
  </script>
</body>
</html>
"""
